#from globalpkg.global_var import sql_query_jsa_step_harm_id
from tools import tool
from globalpkg.global_var import worktaskid
from globalpkg.global_var import workticketid


case = '天津预发布环境-PC-施工作业票'

#times
starttime = tool.starttime
endtime = tool.endtime
now = tool.now
code = tool.ran_code_with_str()

#作业任务名称
name = tool.ran_name_with_str()
print("施工作业名称：",name)

#用例信息变量定义
testsuit_sgzyp = []
caseinfo = {}
caseinfo['id'] = 1
caseinfo['name'] = ''
caseinfo['result'] = ""
caseinfo['url'] = ''
caseinfo['data'] = ''
caseinfo['sign'] =''
caseinfo['flag'] = ''
caseinfo['isactive'] = ''

count =0
host='https://tjsh.ushayden.com'
worktaskid = worktaskid + 1
dhworkticketid = workticketid + 4
sxticketid = workticketid + 5
lsydticketid = workticketid + 2
dtworkid = workticketid + 3
mbcdticketid = workticketid + 6
dzticketid = workticketid + 7
gcticketid = workticketid + 8
xkzticketid = workticketid + 1
#用例信息
caseinfo['id'] = 1
caseinfo['name'] = '施工作业票保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_GB_SGZY/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TICKET_GB_SGZY&0.7809621619087208&contentType=json&ajax=true&tid=2000000002404'
caseinfo['url'] = host+ url
#施工作业票草稿数据
data = {
	"tableName": "hse_work_ticket",
	"delaynum": "999",
	"applyunitname": "天津石化公司",
	"equipmentname": "",
	"worktype__name": "施工作业",
	"worktype": "xkz",
	"ishas_wtd": "0",
	"worktype_name": "施工作业票",
	"territorialunitid": "2000000008565",
	"istask": "1",
	"territorialunitname": "天津石化公司",
	"territorialunitcode": "0001",
	"applyunitid": "2000000008565",
	"ticketdealphoto": "0",
	"workstatus": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": "",
	"tasktype": "",
	"projecttype": "repaire",
	"worklevel": "high_risk",
	"iscontractor": "0",
	"other_worktype": "xkz,dh,sx,mbcd,gc,dz,lsyd,dt,fcgzy",
	"hassafetyplan": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"isgas_detection": "",
	"close_type": "",
	"lock_status": "",
	"hse_notice_id": 1000000131631,
	"notice_code": "030000939252",
	"workname": name,
	"equipmentnumber": "weihao-data",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"site": "api-didian",
	"medium": "介质",
	"temperature": "33",
	"pressure": "1024",
	"workcontent": "挖掘机",
	"planstarttime": starttime,
	"planendtime": endtime,
	"other_worktype_name": "施工作业票,动火作业,受限空间,盲板抽堵,高处作业,吊装作业,临时用电,动土作业,非常规作业"
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

# caseinfo['id'] = 2
# caseinfo['name'] = 'JSA模板保存'
# caseinfo['isactive'] = 1
# #拼写URL
# #http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
# url = '/hse/HSE_JSA_TEMPLETE_NEW/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_JSA_TEMPLETE_NEW&0.5418943903112656&contentType=json&ajax=true&tid=2000000002404'
# caseinfo['url'] = host+ url
# #JSA模板数据
# data = {
# 	"tableName": "hse_jsa_templete",
# 	"temp_type": "aqfx",
# 	"isnew": "1",
# 	"dataStatus": 0,
# 	"ver": 1,
# 	"created_by": "",
# 	"created_dt": now,
# 	"updated_by": "",
# 	"updated_dt": now,
# 	"df": 0,
# 	"tenantid": 2000000002404,
# 	"ts": "",
# 	"isenable": "1",
# 	"orgname": "天津石化公司",
# 	"orgid": 2000000008565,
# 	"temp_name": name
# }
# caseinfo['data'] =data
# testsuit_sgzyp.append(caseinfo.copy())
#
# caseinfo['id'] = 3
# caseinfo['name'] = 'JSA步骤保存'
# caseinfo['isactive'] = 1
# #拼写URL
# #http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
# url = '/hse/HSE_JSA_TEMP_STEP_NEW/cardSave?parentEntityId=2000000000280&parentFuncCode=HSE_JSA_TEMPLETE_NEW&topEntityId=2000000000280&topFuncCode=HSE_JSA_TEMPLETE_NEW&0.9834370508103107&contentType=json&ajax=true&tid=2000000002404'
# caseinfo['url'] = host+ url
# #JSA模板数据
# data = {
# 	"tableName": "hse_jsa_temp_step",
# 	"jsa_templete_id": 2000000000280,
# 	"dataStatus": 0,
# 	"ver": 1,
# 	"created_by": "",
# 	"created_dt": now,
# 	"updated_by": "",
# 	"updated_dt": now,
# 	"df": 0,
# 	"tenantid": 2000000002404,
# 	"ts": "",
# 	"worktype": "",
# 	"step_name": name,
# 	"step_code": "1"
# }
# caseinfo['data'] =data
# testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 2
caseinfo['name'] = '作业任务保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.6181764271364318&contentType=json&ajax=true&tid=2000000002404'
caseinfo['url'] = host+ url
#作业任务数据
data = {
	"tableName": "hse_work_task",
	"ischoisedevice": "0",
	"owner_name": "管理员",
	"work_appoint_name": "",
	"territorialunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"jsa_code": "",
	"workstatus": "draft",
	"autorisklevel": 0,
	"status": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": "",
	"projecttype": "repaire",
	"work_property": "rush_to_repair",
	"is_explosion_proof_area": "0",
	"iscontractor": "0",
	"is_crossed": "0",
	"gas_standard_type": "",
	"eq_position": "",
	"workticket_name": name,
	"workticketid": xkzticketid,
	"hse_notice_id": 1000000131631,
	"notice_code": "030000939252",
	"eqp_id": "",
	"eqp_code": "",
	"con_personid": "",
	"workunitname": "天津石化公司",
	"workunit": 2000000008565,
	"workcontent": "挖掘机",
	"worktickettype": "dh,sx,mbcd,gc,dz,lsyd,dt,fcgzy",
	"worktickettype_name": "动火作业,受限空间,盲板抽堵,高处作业,吊装作业,临时用电,动土作业,非常规作业",
	"party_a_id": "",
	"party_a_name": "",
	"workunit_person_id": "",
	"workunit_person_name": "",
	"workprojectid": "",
	"workprojectname": "",
	"meqp_id": "",
	"meqp_code": "",
	"register_time": now,
	"planstarttime": starttime,
	"planendtime": endtime,
	"site": "api-didian",
	"workname": name,
	"owner_id": 2000000016686,
	"work_position_id": 2000000005308,
	"work_position_name": "天津测试",
	"work_position_point": "117.419288,38.844993",
	"mandatory": 1,
	"poison": "api-weixianwu"
}

caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 3
caseinfo['name'] = '动火票保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654127999825&0.5352415650758255&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,dhworkticketid)
caseinfo['url'] = host+ url

#动火票数据
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654127999825,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": dhworkticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "dh",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "gb_dh_workLevel02",
	"site": "api-didian",
	"workway": "gb_dhfs02",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": "1",
	"gas_aging": 2,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "动火作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": "0"
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 4
caseinfo['name'] = '受限票保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_SX/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654127999876&0.7637517217667551&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,sxticketid)
caseinfo['url'] = host+ url
#受限票数据
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654127999876,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": sxticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "sx",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "gb_sx_workLevel02",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "油气",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "危害",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": "1",
	"gas_aging": 2,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "受限空间",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": "0"
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 5
caseinfo['name'] = '盲板抽堵保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_MBCD/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654130239299&0.9388415625519175&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,mbcdticketid)
caseinfo['url'] = host+ url
#盲板抽堵票数据
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654130239299,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": mbcdticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "mbcd",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "sbgd-name",
	"medium": "youqi",
	"temperature": "33",
	"pressure": "1024",
	"blindplate_material": "mangbancaizhi",
	"blindplate_spec": "8*8",
	"blindplate_code": "mb-1",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "chou",
	"gasket_material": "橡胶",
	"gasket_spec": "3*3",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": "0",
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": "api-data",
	"worktype_name": "盲板抽堵",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 6
caseinfo['name'] = '高处作业保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_GC/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654128000082&0.7977622176062364&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,gcticketid)
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654128000082,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": gcticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "gc",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "gb_gc_workLevel02",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "高处作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 7
caseinfo['name'] = '吊装作业保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_DZ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654128000031&0.874746847627214&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,dzticketid)
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654128000031,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": dzticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "dz",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "gb_dz_workLevel01",
	"site": "api-didian",
	"workway": "",
	"planstarttime":starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "100t",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "大吊车",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "吊装作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 8
caseinfo['name'] = '临时用电作业票保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_LSYD/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654127999724&0.04435546768951926&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,lsydticketid)
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654127999724,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": lsydticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "lsyd",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "未知电源接入点",
	"workvoltage": "380",
	"equipmentandpower": "未知用电设备",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "100",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "临时用电",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())

caseinfo['id'] = 9
caseinfo['name'] = '动土作业票保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_TICKET_DT/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1654127999773&0.7196459975156992&contentType=json&ajax=true&tid=2000000002404'%(worktaskid,worktaskid,dtworkid)
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_work_ticket",
	"territorialdeptname": "",
	"proposer_id": "",
	"is_send_check_gas": "",
	"otherattaches": "",
	"owner_id": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"jsa_code": "",
	"register_time": now,
	"relation": "",
	"territorialdeptid": "",
	"iscontractor": "",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"close_time": "",
	"safedistance": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"eqp_id": "",
	"issjtssxzy": "",
	"other_worktype": "",
	"hse_notice_id": "",
	"notice_code": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"guid": "",
	"work_position_point": "117.419288,38.844993",
	"workprojectname": "",
	"excavation_eqp": "",
	"territorialunitcode": "",
	"pipeline_level": "",
	"replacement": "",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654127999773,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": dtworkid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "dt",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": "api-data",
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000005308,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "动土作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "天津测试",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())


caseinfo['id'] = 10
caseinfo['name'] = '承包商承接数据复制'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_WORK_APPOINT_CONTRACTOR_UNDERTAKE/saveAndCopy?parentEntityId=&parentFuncCode=&topEntityId=2000000000920&topFuncCode=HSE_WORK_APPOINT_CONTRACTOR_UNDERTAKE&dataId=2000000000920&0.7788808446503936&contentType=json&ajax=true&tid=2000000002404'
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_work_appoint",
	"task_worktype_code": "",
	"equt_name": "",
	"created_by_name_nick": "tj",
	"worktaskid_no": 0,
	"cywlqfyxzz": "",
	"isreport": "",
	"specialenvironment": "",
	"created_by_name": "管理员",
	"worklevel_dh": "",
	"iscontainplayday": 0,
	"worktype_name": "施工作业票,动火作业,受限空间,临时用电",
	"workers": "",
	"worktypename": "施工作业票,动火作业,受限空间,临时用电",
	"worklevel_gx": "",
	"device_id": "",
	"task_worktype_name": "",
	"workunitname_con": "",
	"standardmaintenance": "",
	"worklevel_sx": "",
	"material_medium": "",
	"project_leaders": "",
	"risksmeasures": "",
	"issjtssxzy": "",
	"hse_notice_id": 1,
	"notice_code": "无",
	"isupgradedh": "",
	"isdzdh": "",
	"worklevel_gc": "",
	"persistent_type": "",
	"territorialunitcode": "0001011015",
	"worklevel_dz": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000016686,
	"created_dt": "2021-01-19 09:56:44",
	"updated_by": 2000000016686,
	"updated_dt": "2021-01-19 10:01:01",
	"df": 0,
	"tenantid": 2000000002404,
	"ts": "",
	"work_appoint_id": 2000000000920,
	"code": "",
	"iscontractor": "1",
	"workunit": 2000000009178,
	"workunitname": "万全公司",
	"workunitname_no": "万全公司",
	"workcontent": "",
	"workname": "除锈作业",
	"territorialunitid": 2000000009572,
	"territorialunitname": "油品车间",
	"work_position_id": 2000000003179,
	"appointstarttime": "2021-01-19 12:00:00",
	"appointendtime": "2021-01-19 17:30:00",
	"work_position_name": "测试位置",
	"status": "approval",
	"constructionscheme": 0,
	"wf_current_user": "2000000016686",
	"wf_audit_state": "2",
	"wf_create_user": 2000000016686,
	"wf_type": "4",
	"wf_instance": 2000000015550,
	"wf_current_nodeid": "2000000031953",
	"wf_audit_time": "2021-01-19 10:03:46",
	"worktype": "xkz,dh,sx,lsyd",
	"worksite": "航煤罐区",
	"equipmentnumber": "",
	"projecttype": "",
	"isspecialcondition": "",
	"specialcondition": "",
	"iscontainfireday": 0
}
caseinfo['data'] =data
testsuit_sgzyp.append(caseinfo.copy())


#用例信息
caseinfo['id'] = 11
caseinfo['name'] = '施工作业票送交'
caseinfo['isactive'] = 1
#拼写预约URL
#%(xkzticketid,xkzticketid)
url = '/hse/HSE_WORK_TICKET_GB_SGZY/wfSendShow?parentEntityId=&parentFuncCode=&topEntityId=2000000095900&topFuncCode=HSE_WORK_TICKET_GB_SGZY&dataId=2000000095900&ts=1655518105577&0.4238209574662122&contentType=json&ajax=true&tid=2000000002404'
caseinfo['url'] = host+ url
#施工作业票
data = {
	"tableName": "hse_work_ticket",
	"proposer_id": "",
	"otherattaches": "",
	"owner_id": "",
	"relevantdoc": "",
	"jsa_code": "",
	"relation": "",
	"territorialdeptid": "",
	"workprojectid": "",
	"owner_name": "",
	"tasktype": "",
	"proposer": "",
	"territorialdeptcode": "",
	"equipmentname": "",
	"close_time": "",
	"invoicingunitname": "",
	"invoicingunit": "",
	"eqp_id": "",
	"other_worktype": "dh,sx,mbcd,gc,dz,lsyd,dt,fcgzy",
	"hse_notice_id": 1000000131631,
	"notice_code": "030000939252",
	"guid": "",
	"work_position_point": "",
	"workprojectname": "",
	"pipeline_level": "",
	"replacement": "",
	"territorialdeptname": "",
	"is_send_check_gas": "",
	"radiosourcenum": "",
	"register_time": "",
	"iscontractor": "0",
	"risk_rank": "",
	"meqp_code": "",
	"jsaid": "",
	"audit_starttime": "",
	"audit_endtime": "",
	"clause": "",
	"other_worktype_name": "动火作业,受限空间,盲板抽堵,高处作业,吊装作业,临时用电,动土作业,非常规作业",
	"worktype__name": "施工作业",
	"safedistance": "",
	"meqp_id": "",
	"workunit_person_name": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"con_personid": "",
	"eqp_code": "",
	"excavation_eqp": "",
	"territorialunitcode": "0001",
	"workunit_person_id": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000587804,
	"created_dt": now,
	"updated_by": 2000000587804,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000002404,
	"ts": 1654513463146,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "repaire",
	"is_pause": 0,
	"workticketid": 2000000067245,
	"worktaskid": "",
	"equipmentnumber": "weihao-data",
	"worktype": "xkz",
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"applyunitid": 2000000008565,
	"applyunitname": "天津石化公司",
	"worknumber": "",
	"worklevel": "high_risk",
	"site": "api-didian",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "挖掘机",
	"workunit": 2000000008565,
	"workunitname": "天津石化公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "介质",
	"temperature": "33",
	"pressure": "1024",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "张海",
	"updated_by_name": "张海",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 999,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": "",
	"isgas_detection": "0",
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": "",
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": "",
	"worktype_name": "施工作业票",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000587804,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": "0",
	"istask": ""
}
caseinfo['data'] =data
#testsuit_sgzyp.append(caseinfo.copy())

#用例信息
caseinfo['id'] = 12
caseinfo['name'] = '盲板管理-保存'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = '/hse/HSE_TICKET_MBCD/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_TICKET_MBCD&0.2550397275279832&contentType=json&ajax=true&tid=2000000002404'
caseinfo['url'] = host+ url
#
data = {
	"tableName": "hse_ticket_mbcd",
	"columnValues": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": "0",
	"tenantid": 2000000002404,
	"ts": "",
	"blind_type": "",
	"workstatus": "",
	"normalproductionstatus": "",
	"commenceperiodstatus": "",
	"downmaintenancestatus": "",
	"mbcdnumber": code,
	"territorialunitid": 2000000008565,
	"territorialunitname": "天津石化公司",
	"territorialunitcode": "0001",
	"medium": "油气",
	"temperature": "34",
	"pressure": "1024",
	"worksite": "未知"
}
caseinfo['data'] =data
#testsuit_sgzyp.append(caseinfo.copy())