#from globalpkg.global_var import sql_query_jsa_step_harm_id
from tools import tool
#from globalpkg.global_var import tsi
from globalpkg.global_var import workticketid
from globalpkg.global_var import worktaskid
'''
from globalpkg.global_var import worktaskid1
from globalpkg.global_var import jsaid
from globalpkg.global_var import safeclarid
from globalpkg.global_var import sql_query_work_appointid
from globalpkg.global_var import sql_query_jsastepid
from globalpkg.global_var import sql_query_jsa_step_measure_id
from tools import getdata
'''
case = '产品测试环境-PC-作业许可-任务-安全-申请-作业票提交'

#times
starttime = tool.starttime
endtime = tool.endtime
now = tool.now

#作业任务名称
name = tool.ran_name_with_str()
print("作业任务名称：",name)

#用例信息变量定义
testsuit = []
caseinfo = {}
caseinfo['id'] = 1
caseinfo['name'] = ''
caseinfo['result'] = ""
caseinfo['url'] = ''
caseinfo['data'] = ''
caseinfo['sign'] =''
caseinfo['flag'] = ''
caseinfo['isactive'] = ''

count =0
#用例信息
caseinfo['id'] = 1
caseinfo['name'] = '作业任务添加'
caseinfo['isactive'] = 1
#拼写预约URL
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.19129330803343048&contentType=json&ajax=true&tid=2000000002503
url = 'http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.1050740235820895&contentType=json&ajax=true&tid=2000000002503'
caseinfo['url'] = url
#动火作业
data = {
	"tableName": "hse_work_task",
	"ischoisedevice": "0",
	"work_appoint_name": "",
	"applyunitname": "现场总管演示租户",
	"applyunitid": 2000000009055,
	"jsa_code": "",
	"workstatus": "draft",
	"autorisklevel": 0,
	"status": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": starttime,
	"updated_by": "",
	"updated_dt": starttime,
	"df": 0,
	"tenantid": 2000000002503,
	"ts": "",
	"projecttype": "",
	"isspecialcondition": "",
	"work_property": "",
	"iscontractor": "0",
	"gas_standard_type": "",
	"eq_position": "",
	"territorialunitid": 2000000009055,
	"territorialunitname": "现场总管演示租户",
	"territorialunitcode": "0001",
	"work_position_id": 2000000003328,
	"work_position_name": "奥体中心",
	"workunit": 2000000009055,
	"workunitname": "现场总管演示租户",
	"workunitname_no": "",
	"site": "测试地点-1",
	"workname": name,
	"worktickettype_name": "动火作业",
	"worktickettype": "dh",
	"planstarttime": starttime,
	"planendtime": endtime
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

caseinfo['id'] = 2
caseinfo['name'] = '作业任务提交'
caseinfo['isactive'] = 1
worktaskid=worktaskid+1
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/hse_work_task_submit?parentEntityId=&parentFuncCode=&topEntityId=2000100006956&topFuncCode=HSE_WORK_TASK&dataId=2000100006956&0.4366273384106416&contentType=json&ajax=true&tid=2000000002503
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/hse_work_task_submit?parentEntityId=&parentFuncCode=&topEntityId=2000100006960&topFuncCode=HSE_WORK_TASK&dataId=2000100006960&0.6795796836111767&contentType=json&ajax=true&tid=2000000002503
url = 'http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TASK/hse_work_task_submit?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&0.4366273384106416&contentType=json&ajax=true&tid=2000000002503'%(worktaskid,worktaskid)
caseinfo['url'] = url
#动火作业
data = {
	"tableName": "hse_work_task",
	"worklevel_wj": "",
	"workway_wj": "",
	"drawshow": "",
	"workernumber": "",
	"cywlqfyxzz": "",
	"project_name": "",
	"workway_gc": "",
	"autorisklevel": 0,
	"ischoisedevice": 0,
	"othercontent": "",
	"ishasworker": "",
	"hasdrawpaper": "",
	"hassafetyplan": "",
	"worker": "",
	"detect_position": "",
	"work_environment": "",
	"constructionscheme": "",
	"task_worktype_name": "",
	"workunitname_con": "",
	"pressure": "",
	"standardmaintenance": "",
	"attaches": "",
	"worknumber": "",
	"guid": "",
	"is_delay": "",
	"istemplate": "",
	"worklevel_dz": "",
	"task_worktype_code": "",
	"other": "",
	"hasrescueplan": "",
	"ticketform": "",
	"workway_dz": "",
	"medium": "",
	"worklevel_dh": "",
	"worktools": "",
	"workway_dh": "",
	"equipmentcode": "",
	"temperature": "",
	"card_code": "",
	"workway_gx": "",
	"worklevel_gx": "",
	"reminder": "",
	"reminderid": "",
	"worktickettype_name": "动火作业",
	"worklevel_sx": "",
	"material_medium": "",
	"risksmeasures": "",
	"risk_level": "",
	"isrecord": "",
	"worklevel_gc": "",
	"workway_shex": "",
	"persistent_type": "",
	"flights": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000017571,
	"created_dt": starttime,
	"updated_by": 2000000017571,
	"updated_dt": starttime,
	"df": 0,
	"tenantid": 2000000002503,
	"ts": "",
	"worktaskid": worktaskid,
	"workname": name,
	"work_position_name": "奥体中心",
	"work_appoint_name": "",
	"actualstarttime": "",
	"actualendtime": "",
	"isgas_detection": "",
	"delayreason": "",
	"cancelreason": "",
	"pause": 0,
	"isupgrade": "",
	"sourcetaskid": "",
	"nlglnumber": "",
	"isreport": "",
	"iswfnotreport": 0,
	"gas_standard_type": "",
	"parentid": "",
	"lsydticketid": "",
	"dqyzticketid": "",
	"dqezticketid": "",
	"task_pause": "",
	"device_id": "",
	"territorialunitid": 2000000009055,
	"territorialunitname": "现场总管演示租户",
	"site": "测试地点-1",
	"work_property": "",
	"equipmentnumber": "",
	"workunit": 2000000009055,
	"workunitname": "现场总管演示租户",
	"projecttype": "",
	"iscontractor": "0",
	"planstarttime": starttime,
	"planendtime": endtime,
	"worktickettype": "dh",
	"workstatus": "draft",
	"applyunitid": 2000000009055,
	"applyunitname": "现场总管演示租户",
	"created_by_name": "admin2021",
	"updated_by_name": "admin2021",
	"workcontent": "",
	"woid": "",
	"wo_code": "",
	"territorialunitcode": "0001",
	"equt_position": "",
	"position_name": "",
	"equipmentname": "",
	"safeclar": "",
	"safecode": "",
	"work_position_id": 2000000003328,
	"jsa_code": "",
	"jsaid": "",
	"work_appoint_id": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"task_risklevel": "",
	"task_closereason": "",
	"task_closetype": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000017571,
	"wf_instance": "",
	"wf_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"jobstatus": "",
	"weekplanid": "",
	"plan_type": 3,
	"gasdetecttype": "",
	"close_type": "",
	"closereason": "",
	"jsa_code2": "",
	"jsaid2": "",
	"isproprietor": "",
	"planendtime_org": "",
	"specialenvironment": "",
	"gas_aging": "",
	"safetyanalysisid": "",
	"safetyanalysiscode": "",
	"isspecialcondition": "",
	"specialcondition": "",
	"task_risklevel_org": "",
	"status": "draft",
	"eq_position": ""
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

caseinfo['id'] = 3
caseinfo['name'] = '作业票保存'
caseinfo['isactive'] = 1
workticketid = workticketid+1
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=2000100006960&parentFuncCode=HSE_WORK_TASK&topEntityId=2000100006960&topFuncCode=HSE_WORK_TASK&dataId=2000100008242&ts=1624417016735&0.4432067065357832&contentType=json&ajax=true&tid=2000000002503
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=2000100006959&parentFuncCode=HSE_WORK_TASK&topEntityId=2000100006959&topFuncCode=HSE_WORK_TASK&dataId=2000100008241&ts=1624417658853&0.09235504041001308&contentType=json&ajax=true&tid=2000000002503
url = 'http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1624417658853&0.09235504041001308&contentType=json&ajax=true&tid=2000000002503'%(worktaskid,worktaskid,workticketid)
caseinfo['url'] = url
#动火作业
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"otherattaches": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"relation": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"risk_rank": "",
	"isrecord": "",
	"guid": "",
	"excavation_eqp": "",
	"territorialunitcode": "0001",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"replacement": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000017571,
	"created_dt": starttime,
	"updated_by": 2000000017571,
	"updated_dt": starttime,
	"df": 0,
	"tenantid": 2000000002503,
	"ts": 1624417658853,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "dh",
	"territorialunitid": 2000000009055,
	"territorialunitname": "现场总管演示租户",
	"applyunitid": 2000000009055,
	"applyunitname": "现场总管演示租户",
	"worknumber": "",
	"worklevel": "gb_dh_workLevel02",
	"site": "测试地点-1",
	"workway": "gb_dhfs01",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "",
	"workunit": 2000000009055,
	"workunitname": "现场总管演示租户",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "admin2021",
	"updated_by_name": "admin2021",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000003328,
	"isgas_detection": "1",
	"gas_aging": "2",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "动火作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "奥体中心",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000017571,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

caseinfo['id'] = 4
caseinfo['name'] = '作业票提交'
caseinfo['isactive'] = 1
#workticketid = workticketid+1
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/hse_work_ticket_submit?parentEntityId=2000100007052&parentFuncCode=HSE_WORK_TASK&topEntityId=2000100007052&topFuncCode=HSE_WORK_TASK&dataId=2000100008352&ts=1624425675527&0.9097665751101249&contentType=json&ajax=true&tid=2000000002503
#http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/hse_work_ticket_submit?parentEntityId=2000100007051&parentFuncCode=HSE_WORK_TASK&topEntityId=2000100007051&topFuncCode=HSE_WORK_TASK&dataId=2000100008351&ts=1624425468636&0.23738799471216576&contentType=json&ajax=true&tid=2000000002503
url = 'http://v3-test-linux-hse.hd-cloud.com/hse/HSE_WORK_TICKET_DH/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=1624425468636&0.23738799471216576&contentType=json&ajax=true&tid=2000000002503'%(worktaskid,worktaskid,workticketid)
caseinfo['url'] = url
#动火作业
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"otherattaches": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"relation": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"risk_rank": "",
	"isrecord": "",
	"guid": "",
	"excavation_eqp": "",
	"territorialunitcode": "0001",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"replacement": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000017571,
	"created_dt": starttime,
	"updated_by": 2000000017571,
	"updated_dt": starttime,
	"df": 0,
	"tenantid": 2000000002503,
	"ts": 1624425468636,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"isfillticket": "",
	"task_pause": "",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketid,
	"worktaskid": worktaskid,
	"equipmentnumber": "",
	"worktype": "dh",
	"territorialunitid": 2000000009055,
	"territorialunitname": "现场总管演示租户",
	"applyunitid": 2000000009055,
	"applyunitname": "现场总管演示租户",
	"worknumber": "",
	"worklevel": "gb_dh_workLevel02",
	"site": "测试地点-1",
	"workway": "gb_dhfs01",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "",
	"workunit": 2000000009055,
	"workunitname": "现场总管演示租户",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "admin2021",
	"updated_by_name": "admin2021",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000003328,
	"isgas_detection": "1",
	"gas_aging": 2,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "动火作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "奥体中心",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000017571,
	"wf_instance": "",
	"wf_type": "",
	"isabnormal": "",
	"abnormaltype": "",
	"ishas_wtd": ""
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())